# Generated by Django 5.2.1 on 2025-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidade', models.CharField(choices=[('Esteticista', 'Esteticista'), ('Massoterapeuta', 'Massoterapeuta'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Dermatologista', 'Dermatologista'), ('Outro', 'Outro')], max_length=30)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Percentual da comissão (%)', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
