services:
  - type: web
    name: erp-estetica
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn erp_estetica.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
