# Generated by Django 5.2.1 on 2025-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('FIXA', 'Fixa'), ('VARIAVEL', 'Variável'), ('ADMIN', 'Administrativa'), ('COMISSAO', 'Comissão'), ('INSUMO', 'Insumo'), ('OUTRA', 'Outra')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
