# Generated by Django 5.2.1 on 2025-05-21 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('aniversario', 'Aniversário'), ('lembrete', 'Lembrete de Agendamento'), ('promocional', 'Promoção'), ('comemorativa', 'Data Comemorativa'), ('personalizada', 'Personalizada')], max_length=20)),
                ('data_disparo', models.DateTimeField(blank=True, null=True)),
                ('mensagem', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destinatarios', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
