# Generated by Django 5.2.1 on 2025-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('starter', 'Starter'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='starter', max_length=10, verbose_name='Categoria'),
        ),
    ]
